// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAIkgUZ39pY_GJaaQSJataNtT9vDS-1tg',
    appId: '1:825168715155:web:1330e48063971313fd1c66',
    messagingSenderId: '825168715155',
    projectId: 'dummmy-9fdb3',
    authDomain: 'dummmy-9fdb3.firebaseapp.com',
    storageBucket: 'dummmy-9fdb3.firebasestorage.app',
    measurementId: 'G-TFWD4Q4CB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0tCMYFcfmxfTqjajPIqN9-2lo5QTdWKI',
    appId: '1:825168715155:android:21fb3ff346aa4376fd1c66',
    messagingSenderId: '825168715155',
    projectId: 'dummmy-9fdb3',
    storageBucket: 'dummmy-9fdb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-LrchZrCw_BbXNAmw71x4skdJUhTEoZs',
    appId: '1:825168715155:ios:43bcdbc6d4186eb3fd1c66',
    messagingSenderId: '825168715155',
    projectId: 'dummmy-9fdb3',
    storageBucket: 'dummmy-9fdb3.firebasestorage.app',
    iosBundleId: 'com.ferozshah.dummmy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-LrchZrCw_BbXNAmw71x4skdJUhTEoZs',
    appId: '1:825168715155:ios:43bcdbc6d4186eb3fd1c66',
    messagingSenderId: '825168715155',
    projectId: 'dummmy-9fdb3',
    storageBucket: 'dummmy-9fdb3.firebasestorage.app',
    iosBundleId: 'com.ferozshah.dummmy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAIkgUZ39pY_GJaaQSJataNtT9vDS-1tg',
    appId: '1:825168715155:web:8e1cce36fa1a0e1cfd1c66',
    messagingSenderId: '825168715155',
    projectId: 'dummmy-9fdb3',
    authDomain: 'dummmy-9fdb3.firebaseapp.com',
    storageBucket: 'dummmy-9fdb3.firebasestorage.app',
    measurementId: 'G-B1XSRCCCG9',
  );
}
